### ISSUE TITLE
Bug: Microsite admin - cannot manage menus

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#314]
As a (not user 1) user who is a microsite admin I cannot edit menus

**Comment by msayoung** [comment]
Also we have the ADD MENU link available, though you can't add a menu. 



![Image](https://user-images.githubusercontent.com/3852805/202742495-290d2a5a-4986-42c6-8f1f-44ff67f992e1.png)

**Comment by ekes** [comment]
If you can edit it as a Microsite Controller then it's just a permissions assigned to microsite admin issue. So can be fixed by finding the permission and adding it to the config in the module.
If you can't do it as Microsite Controller, then... we're in code.

**Comment by msayoung** [comment]
As a Microsite Controller I can edit and add a menu item, although when I save an edited menu item I have an access denied messgae

**Comment by msayoung** [comment]
@ekes this one is still an issue

1. Controller. Can add and edit menu items but on save (after an edit) we see Access Denied
2. Controller and Microsite Admin sees Add new menu link
3. Microsite admin cannot edit menus

**Comment by ekes** [comment]
So [f057faf](https://github.com/localgovdrupal/localgov_microsites_group/commit/f057fafcfac5ee5289567f07c0de17dec4664d3a) should fix this. Requires reinstall, or importing the updated permissions for member and admin.

**Comment by msayoung** [comment]
@ekes thanks

As a microsite admin I can now add menu items and edit them. 

However 

- I still see the "add new menu" button (which I think I shouldnt) 
- Also, when I edit a menu item and save I get an access denied message

**Comment by ekes** [comment]
> I still see the "add new menu" button (which I think I shouldnt) 

Fix for that on its way - another permission

> Also, when I edit a menu item and save I get an access denied message

This one I can't reproduce. You are getting to the 'edit' I understand from that, just after saving you get denied error? 
Testing I'm on 
https://localgov-micro.lndo.site/admin/structure/menu/item/1/edit
and I save it. I'm still on 
https://localgov-micro.lndo.site/admin/structure/menu/item/1/edit
but with the banner message telling me it's been saved.
Where are you getting sent to?

**Comment by msayoung** [comment]
Great! No "Add new menu link" 

@finnlewis  is creating a new issue for the access denied thing

**Comment by finnlewis** [comment]
See https://github.com/localgovdrupal/localgov_microsites_group/issues/332
