### ISSUE TITLE
[3.x] Bug: As Microsite admin can't create a new taxonomy term

### ISSUE THREAD

**Issue by msayoung** [localgovdrupal/localgov_microsites_group#317]
As a microsite admin, add a new Blog author > Save 

The website encountered an unexpected error. Please try again later.
Error: Call to undefined method Drupal\group\Entity\GroupType::hasContentPlugin() in localgov_microsites_group_term_ui_entity_insert() (line 47 of modules/contrib/localgov_microsites_group/modules/localgov_microsites_group_term_ui/localgov_microsites_group_term_ui.module)

The same issue appears for Categories.

**Comment by msayoung** [comment]
Also true for a Controller

**Comment by ekes** [comment]
Think this is already fixed if you pull localgov_microsites_group

**Comment by msayoung** [comment]
I can add terms with no issue except for Blog authors. 
When I save the term I get

The website encountered an unexpected error. Please try again later.
Error: Class "Drupal\group\Entity\GroupContent" not found in group_term_tokens() (line 51 of modules/contrib/group_term/group_term.tokens.inc).
group_term_tokens('term', Array, Array, Array, Object)
call_user_func_array(Object, Array) (Line: 426)
Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object, 'group_term') (Line: 405)
Drupal\Core\Extension\ModuleHandler->invokeAllWith('tokens', Object) (Line: 433)
Drupal\Core\Extension\ModuleHandler->invokeAll('tokens', Array) (Line: 357)
Drupal\Core\Utility\Token->generate('term', Array, Array, Array, Object) (Line: 239)
Drupal\Core\Utility\Token->doReplace(1, 'blog-author/[term:name]', Array, Array, Object) (Line: 189)
Drupal\Core\Utility\Token->replace('blog-author/[term:name]', Array, Array, Object) (Line: 228)
Drupal\pathauto\PathautoGenerator->createEntityAlias(Object, 'update') (Line: 381)
Drupal\pathauto\PathautoGenerator->updateEntityAlias(Object, 'update') (Line: 93)
pathauto_entity_update(Object)
call_user_func_array(Object, Array) (Line: 426)
Drupal\Core\Extension\ModuleHandler->Drupal\Core\Extension\{closure}(Object, 'pathauto') (Line: 405)
Drupal\Core\Extension\ModuleHandler->invokeAllWith('entity_update', Object) (Line: 433)
Drupal\Core\Extension\ModuleHandler->invokeAll('entity_update', Array) (Line: 251)
Drupal\Core\Entity\EntityStorageBase->invokeHook('update', Object) (Line: 903) 
...

However it does create the term

**Comment by msayoung** [comment]
Seems to be an issue with the pathauto pattern ? 
If I delete the pattern then the terms save with no errors

**Comment by ekes** [comment]
I've pushed a change to group_term assuming you've got the repo https://git.drupalcode.org/issue/group_term-3316529 branch 3316529-group-3.x-compatibility which is what the lastest composer is set to.

**Comment by msayoung** [comment]
I'm afraid I'm still seeing the same, and I'm pretty certain I got the most recent commits

![image](https://user-images.githubusercontent.com/3852805/202759461-c815d3e9-dc88-47e0-bcc0-50687d620f8a.png)

**Comment by finnlewis** [comment]
I just did a fresh install.

1. Add 2 microsites.
2. Add two users, admin1, admin2 and assign as admin to the microsites. 
3. Log in as admin1 to microsite1.
4. Got o https://localgov-micro-1.lndo.site/group/1/taxonomy/localgov_blog_author/add
5. I can create blog authors. 
6. BUT I do not see them listed at https://localgov-micro-1.lndo.site/group/1/taxonomy/localgov_blog_author 

8. I then go to https://localgov-micro-2.lndo.site/ and log in as admin2
9. Go to https://localgov-micro-2.lndo.site/group/2/taxonomy/localgov_blog_author 
10. I see no blog authors.
11. I can add other blog authors here for site 2. 
12. BUT I do not see them at https://localgov-micro-2.lndo.site/group/2/taxonomy/localgov_blog_author

**Comment by finnlewis** [comment]
Closing in favour of: https://github.com/localgovdrupal/localgov_microsites_group/issues/319

**Comment by msayoung** [comment]
confirming the original error has gone on a fresh install
